use_default_settings: true
server:
  bind_address: "127.0.0.1"
  port: 8888
  secret_key: "CHANGEME-generate-a-new-secret-key"
search:
  autocomplete: "google"
  default_lang: "en"
  formats:
    - html
    - json
general:
  instance_name: "strix-halo search"
